version: '3.8'
services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    container_name: static_frontend
    ports:
      - "80:80"
    

  